---
# tasks file for octoprint and mjpg_streamer removal.

- name: Disable octoprint and mjpg_streamer services.
  service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  with_items:
    - octoprint
    - mjpg_streamer
  register: disable_service
  ignore_errors: true

- name: Remove files and directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/systemd/system/octoprint.service
    - /etc/systemd/system/mjpg_streamer.service
    - /etc/init.d/octoprint
    - /etc/default/octoprint
    - "{{ install_dir }}/Octoprint"
    - "{{ install_dir }}/.octoprint"
    - "{{ install_dir }}/mjpg-streamer"
    - "{{ install_dir }}/scripts"

- name: Remove dependencies.
  package:
    name: "{{ octoprint_dependencies + mjpg_streamer_dependencies }}"
    state: absent
  when: uninstall_dependencies
